CREATE DATABASE IF NOT EXISTS `grafana`;
GRANT ALL PRIVILEGES ON grafana.* TO 'grafana'@'%' IDENTIFIED BY 'admin12345' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON grafana.* TO 'grafana'@'%' IDENTIFIED BY 'admin12345' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON grafana.* TO 'grafana'@'localhost' IDENTIFIED BY 'admin12345' WITH GRANT OPTION;
FLUSH PRIVILEGES;
